### ISSUE TITLE
Refactoring suggestions

### ISSUE THREAD

**Issue by Mallear** [ekino/docker-buildbox#168]
Hello there,

I would like to suggest some refactoring of docker-buildbox project.

## Template engine

Switching from `.tpl` to jinja2 template, natively supported by Python and avoiding calling `sed` inside a python script.

## One config file to rule them all

External configuration file for variables like extra build arguments or template variables for each image instead of a list of env vars in the CI configuration file.

The goals are both keeping the CI configuration clear and simple AND easing contributors to create/maintain new images.

Each image configuration would look like that: 
```
image_name:
  version:
    cmd_test: [...]
    build_args: [...]
    template_vars: [...]  # if templated Dockerfile
    dockerfile_dir: /path/to/dockerfile  # if Dockerfile's path is not ./<image_name/Dockerfile (ex: java6 image)
```

## Better CLI

`travis.py` script refactoring using Click, Jinja2 template engine and Python Docker client for a better understandable CLI and no more script editing to add new image.

I have though of something like the following: `python travis.py build --image <image_name> --version <image_version>`. Everything else would be managed in the configuration file mentioned earlier.

## Extra point

I think it would be clearer to manage each image in a different docker repository as it will be easier to create meaningful tags and find the latest for the image we want.

For exemple, creating a repository `ekino/<image_name>` for each image will make multi-version images easier to manage. This way we will only have to manage tags like `<version>-latest` or `<version>-<tag_date>`. For me it will make it way easier to use for newcomers or external people.

-------

I have already spent some time on this refactoring to see if everything could be managed. I still have to work on test commands and prettier output logs but everything works.
