### ISSUE TITLE
Cannot connect to the Docker daemon in dind-aws

### ISSUE THREAD

**Issue by mvrkljan** [ekino/docker-buildbox#73]
Hi! Had this working before, but recently getting this error in CI output:

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

This is how gitlab-ci.yml looks like for the stage in question:

```
deploy:staging:
  image: ekino/docker-buildbox:latest-dind-aws
  stage: deploy
  environment:
      name: staging
  script:
    - ./ci/deploy_api.stage.sh
  only:
    - master
  dependencies:
    - build:staging
```

deploy_api.stage.sh:

```
cp _build/stage/rel/api/releases/${VERSION}/api.tar.gz api.tar.gz
docker build -f docker/phoenix/build.df -t ${ECR_API_REPOSITORY}:staging .
eval $(aws ecr get-login)
docker push ${ECR_API_REPOSITORY}:staging
```

Any idea what might need to be updated if there was a change on gitlab side? I'm using public runner available for CE projects.
